export interface HeroSpec {
  id: string;
  name: string;
  tagline: string;
  archetype: string;
  palette: string;
  suit: string;
  emblem: string;
  powers: string;
  powerFx: string;
  transformation: string;
  rescueMove: string;
}

export const HEROES: HeroSpec[] = [
  { id:"sky-spark", name:"Sky Spark", tagline:"Guardian of the open sky", archetype:"wind-and-flight guardian", palette:"pearl white, midnight navy, cyan", suit:"pearl-white aerodynamic suit with midnight-navy side panels, silver-grey gloves and boots, thin cyan energy fins on the forearms", emblem:"a small original triangular prism mark", powers:"air gliding, compressed-wind flight, wind shields and directional air bursts", powerFx:"clean cyan airflow ribbons and tiny luminous particles", transformation:"cyan airflow filaments weave the suit from the shoes upward", rescueMove:"redirect dangerous falling objects with a controlled column of air" },
  { id:"moon-guard", name:"Moon Guard", tagline:"Protector beneath the moon", archetype:"moonlight defender", palette:"deep indigo, silver, pale lavender", suit:"deep-indigo flexible suit with silver shoulder arcs, pale-lavender luminous seams and a smooth open-face crescent visor", emblem:"an original split-circle moonstone mark", powers:"moonlight shields, soft gravity control and protective barriers", powerFx:"silver-lavender rings and floating dust motes", transformation:"bands of moonlight wrap around the body and harden into flexible protective panels", rescueMove:"stabilize collapsing structures inside a low-gravity shield" },
  { id:"volt-runner", name:"Volt Runner", tagline:"Fast as a flash of energy", archetype:"electric speed hero", palette:"charcoal, amber, electric teal", suit:"charcoal kinetic suit with amber panels, teal pulse channels and low-profile insulated boots", emblem:"an original broken-arrow circuit mark", powers:"electric acceleration, rapid movement and safe energy discharge", powerFx:"teal-and-amber sparks tracing curved paths", transformation:"small circuit-like light lines race over the clothes and assemble the kinetic suit", rescueMove:"outrun a spreading hazard and discharge energy into a safe grounding point" },
  { id:"tide-keeper", name:"Tide Keeper", tagline:"Friend of rivers and seas", archetype:"water guardian", palette:"ocean blue, graphite, sea-glass green", suit:"ocean-blue hydro suit with graphite joints, sea-glass translucent gauntlets and streamlined boots", emblem:"an original three-wave knot symbol", powers:"water shaping, pressure shields and controlled currents", powerFx:"transparent water ribbons with sea-glass highlights", transformation:"water beads rise from nearby surfaces and form smooth hydro-fabric layers", rescueMove:"redirect rushing water and carry people to safety on a controlled current" },
  { id:"leaf-sentinel", name:"Leaf Sentinel", tagline:"Nature grows where courage leads", archetype:"nature guardian", palette:"forest green, warm bronze, moss", suit:"forest-green flexible suit with warm-bronze leaf-vein trim and bark-textured forearm guards", emblem:"an original four-point seed mark", powers:"rapid plant growth, vine control and natural cushioning", powerFx:"soft green bioluminescent veins and drifting pollen lights", transformation:"glowing seed-like particles grow into woven plant-fiber armor", rescueMove:"grow a living safety net and brace unstable ground with roots" },
  { id:"stone-pulse", name:"Stone Pulse", tagline:"Strong, steady, kind", archetype:"earth-strength guardian", palette:"slate, copper, turquoise", suit:"slate stone-fiber suit with copper joints, turquoise pulse seams and rounded protective gauntlets", emblem:"an original concentric mountain mark", powers:"earth shaping, vibration sensing and great lifting strength", powerFx:"turquoise pulse rings moving through stone", transformation:"small mineral plates rise from the ground and fuse into flexible stone-fiber panels", rescueMove:"lift debris and reinforce cracked ground without causing further damage" },
  { id:"star-mapper", name:"Star Mapper", tagline:"Finding the safest path", archetype:"cosmic navigation hero", palette:"midnight violet, gold, ice blue", suit:"midnight-violet exploration suit with gold routing lines and ice-blue wrist projectors", emblem:"an original seven-node constellation glyph", powers:"spatial mapping, trajectory prediction and short-range light bridges", powerFx:"gold constellation lines floating in three dimensions", transformation:"constellation points appear around the child and connect into the suit", rescueMove:"project the safest route through danger and create a temporary light bridge" },
  { id:"glow-smith", name:"Glow Smith", tagline:"Build light into hope", archetype:"light-forging hero", palette:"ivory, graphite, warm gold", suit:"ivory-and-graphite maker suit with warm-gold luminous gauntlets and compact tool bands", emblem:"an original interlocking spark-and-anvil shape", powers:"solid-light tools, braces and protective constructs", powerFx:"warm geometric light pieces assembling in midair", transformation:"tiny golden polygons assemble into the suit and tool gauntlets", rescueMove:"forge a temporary light brace, ramp or shield exactly where needed" },
  { id:"shadow-dash", name:"Shadow Dash", tagline:"Quiet steps, brave heart", archetype:"stealth-and-agility guardian", palette:"smoky plum, graphite, mint", suit:"smoky-plum agile suit with graphite panels, mint edge lights and a low-profile open-face hood", emblem:"an original offset-chevron shadow mark", powers:"silent movement, shadow blending and enhanced agility", powerFx:"soft smoky trails with mint edge glints", transformation:"shadows stretch into fabric-like ribbons that wrap into the agile suit", rescueMove:"move unseen through danger to guide trapped people out by the safest route" },
  { id:"bolt-builder", name:"Bolt Builder", tagline:"Every problem has a clever solution", archetype:"young inventor hero", palette:"orange, navy, brushed steel", suit:"orange-and-navy utility suit with brushed-steel forearm tools, clear goggles and compact modular belt", emblem:"an original hex-bolt flower mark", powers:"rapid invention, magnetic tools and helper drones", powerFx:"blueprint-like holograms and small amber status lights", transformation:"modular tool pieces unfold from a glowing wrist band and assemble the suit", rescueMove:"build a quick stabilizer or magnetic lift system from nearby safe materials" },
  { id:"sun-shield", name:"Sun Shield", tagline:"Warm light, strong protection", archetype:"solar protector", palette:"sand gold, white, deep teal", suit:"sand-gold and white protective suit with deep-teal side panels and broad translucent forearm shields", emblem:"an original eight-ray spiral disc", powers:"solar energy storage, radiant shields and controlled heat-free light", powerFx:"soft golden rings and sunlit particles", transformation:"warm light gathers into translucent panels that become solid fabric and shields", rescueMove:"create a broad radiant barrier that protects people from impact and heat" },
  { id:"mist-rider", name:"Mist Rider", tagline:"Move softly through the clouds", archetype:"fog-and-cloud mover", palette:"cloud grey, sky blue, violet", suit:"cloud-grey suit with sky-blue panels, violet mist vents and soft high-grip boots", emblem:"an original looping cloud-knot mark", powers:"fog shaping, cloud stepping and gentle cushioning", powerFx:"cool mist ribbons with violet highlights", transformation:"mist condenses around the child and becomes layered cloud-fiber fabric", rescueMove:"build a soft cloud cushion and guide people through low-visibility danger" },
  { id:"comet-jumper", name:"Comet Jumper", tagline:"Leap beyond the impossible", archetype:"acrobatic momentum hero", palette:"magenta, charcoal, silver", suit:"magenta-and-charcoal kinetic suit with silver flex bands and compact wrist stabilizers", emblem:"an original double-comet arc", powers:"superb agility, wall-assisted leaps and momentum redirection", powerFx:"magenta comet trails and silver sparks", transformation:"two comet-like light trails spiral around the body and solidify into flexible suit layers", rescueMove:"use rapid controlled leaps to secure multiple danger points in seconds" },
  { id:"crystal-warden", name:"Crystal Warden", tagline:"Clear mind, strong shield", archetype:"crystal barrier guardian", palette:"rose quartz, graphite, ice white", suit:"graphite suit with rose-quartz translucent armor edges and ice-white joint fabric", emblem:"an original faceted diamond-ring mark", powers:"crystal barriers, protective domes and light refraction", powerFx:"transparent faceted planes with soft rose light", transformation:"harmless crystal facets grow in the air and fold into flexible protective pieces", rescueMove:"raise a clear protective barrier and redirect debris away from people" },
  { id:"river-scout", name:"River Scout", tagline:"Always find a way through", archetype:"rescue-and-navigation hero", palette:"teal, mustard, navy", suit:"teal rescue suit with mustard flotation panels, navy joints and compact navigation wrist bands", emblem:"an original compass-ripple mark", powers:"swift swimming, current reading and rescue-line projection", powerFx:"teal current arrows and soft map lines", transformation:"glowing route lines wrap around the child and become a practical rescue suit", rescueMove:"read the safest route and deploy a light rescue line across water or gaps" },
  { id:"flare-song", name:"Flare Song", tagline:"Courage has a rhythm", archetype:"sound-and-light hero", palette:"coral, purple, warm white", suit:"coral-and-purple resonance suit with warm-white speakerless pulse panels at the wrists", emblem:"an original three-ring wave mark", powers:"safe sound pulses, light waves and vibration damping", powerFx:"concentric coral-and-white wave rings", transformation:"gentle musical pulses appear as light rings and weave the suit around the child", rescueMove:"cancel dangerous vibrations and send a guiding light pulse through smoke or darkness" },
  { id:"aurora-knight", name:"Aurora Knight", tagline:"Carry the northern light", archetype:"aurora energy guardian", palette:"deep violet, emerald, icy blue", suit:"deep-violet suit with emerald and icy-blue flowing light panels and rounded shoulder guards", emblem:"an original folded-ribbon star mark", powers:"aurora barriers, energy ribbons and cold-safe illumination", powerFx:"emerald-violet aurora ribbons", transformation:"aurora ribbons descend and wrap into luminous fabric panels", rescueMove:"form a wide aurora canopy that shields and guides people to safety" },
  { id:"time-ticker", name:"Time Ticker", tagline:"A second can make a difference", archetype:"time-field helper", palette:"bronze, navy, aqua", suit:"navy suit with bronze circular joints, aqua timing bands and a small open wrist dial with no numerals", emblem:"an original nested-hourglass spiral", powers:"brief local slow-motion fields and motion prediction", powerFx:"aqua rings with bronze tick-like particles", transformation:"concentric rings pass over the child and leave the finished suit behind", rescueMove:"slow a falling or moving hazard just long enough for everyone to escape" },
  { id:"dream-lantern", name:"Dream Lantern", tagline:"Hope lights the dark", archetype:"hope-and-dream guardian", palette:"cream, lilac, amber", suit:"cream-and-lilac soft armor with amber lantern-like glow panels and flowing sash details", emblem:"an original floating-square lantern mark", powers:"calming light, protective dream bubbles and fear reduction", powerFx:"warm amber lantern motes and translucent lilac bubbles", transformation:"small lantern motes gather and weave into soft luminous armor", rescueMove:"calm a frightened crowd and form protective bubbles around those in immediate danger" },
  { id:"storm-patch", name:"Storm Patch", tagline:"Fix the weather, help the neighborhood", archetype:"weather helper", palette:"cobalt, lime, storm grey", suit:"cobalt rescue suit with lime weather sensors, storm-grey flexible panels and open-face hood", emblem:"an original stitched-cloud compass mark", powers:"small-scale wind and rain steering, lightning-safe grounding and storm sensing", powerFx:"cobalt airflow arcs with lime sensor sparks", transformation:"raindrops and wind lines stitch themselves into the weather-rescue suit", rescueMove:"steer a dangerous gust or downpour away from people and into a safe open area" },
];

export function getHero(id?: string): HeroSpec {
  return HEROES.find((hero) => hero.id === id) ?? HEROES[0];
}
