/**
 * POST /api/assemble
 *
 * Free path: build the print-ready PDF from images the user generated by hand.
 * Multipart form with name/age/gender + image files (named 01.png, 02.png, …).
 * Returns the PDF directly — assembly takes a few seconds, so no polling needed.
 *
 * CRITICAL: Uses matchImportedFiles() as the single authoritative import
 * resolver. Images are keyed by slotId, never by raw numeric index.
 */

import { NextResponse } from "next/server";
import { z } from "zod";
import {
  assembleFromImages,
  type ProvidedImage,
} from "@/lib/manual/assemble";
import {
  matchImportedFiles,
  type LegacyInterpretation,
} from "@/lib/manual/importMatch";
import { runPreflight, type PreflightFile } from "@/lib/print/preflight";
import { sanitizeTransform, type ArtworkTransform } from "@/lib/print/artworkTransform";
import { saveRun } from "@/lib/generate/saveRun";
import { bookFilename } from "@/lib/story/registry";
import { resolveLayoutPlan, type LayoutMode } from "@/lib/story/layoutPlan";
import type { ChildProfile } from "@/lib/story/types";
import { directVideoTarget } from "@/lib/story/qr";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

const profileSchema = z.object({
  name: z.string().trim().min(1, "Name is required").max(40),
  age: z.coerce.number().int().min(0).max(18),
  gender: z.enum(["boy", "girl", "neutral"]),
});

export async function POST(request: Request): Promise<Response> {
  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return NextResponse.json(
      { error: "Expected multipart/form-data." },
      { status: 400 },
    );
  }

  const parsed = profileSchema.safeParse({
    name: form.get("name"),
    age: form.get("age"),
    gender: form.get("gender"),
  });
  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues[0]?.message ?? "Invalid input." },
      { status: 400 },
    );
  }
  const child: ChildProfile = parsed.data;

  const files = form
    .getAll("images")
    .filter((f): f is File => f instanceof File && f.size > 0);
  if (files.length === 0) {
    return NextResponse.json(
      { error: "Please add your generated images (named 01.png, 02.png, …)." },
      { status: 400 },
    );
  }

  let transformsMap: Record<string, ArtworkTransform> = {};
  const rawTransforms = form.get("transforms");
  if (typeof rawTransforms === "string") {
    try {
      transformsMap = JSON.parse(rawTransforms);
    } catch {
      /* ignore invalid JSON */
    }
  }

  const bookId = (form.get("bookId") as string) || undefined;
  const profileId = (form.get("profileId") as string) || undefined;
  const isDraft = form.get("draft") === "true";
  const preflightOnly = form.get("preflightOnly") === "true";
  const confirmLegacyOffsetRecovery = form.get("confirmLegacyOffsetRecovery") === "true";
  const rawLegacyInterpretation = form.get("legacyInterpretation") as string | null;
  const legacyInterpretation: LegacyInterpretation | undefined =
    rawLegacyInterpretation === "SHIFT_PLUS_TWO" || rawLegacyInterpretation === "KEEP_NUMERIC_SLOTS"
      ? rawLegacyInterpretation
      : undefined;
  const acknowledgeQualityWarnings = form.get("acknowledgeQualityWarnings") === "true";
  const rawMode = ((form.get("layoutMode") as string) || (form.get("mode") as string)) || null;
  const mode: LayoutMode | undefined = rawMode === "custom-spreads" || rawMode === "standard-single" ? rawMode : undefined;
  let customSpreads: any = undefined;
  const rawSpreads = form.get("customSpreads");
  if (typeof rawSpreads === "string") {
    try {
      customSpreads = JSON.parse(rawSpreads);
    } catch {
      /* ignore invalid JSON */
    }
  }

  let qualityAcknowledgements: Record<string, any> | undefined = undefined;
  const rawQualityAcknowledgements = form.get("qualityAcknowledgements");
  if (typeof rawQualityAcknowledgements === "string") {
    try {
      qualityAcknowledgements = JSON.parse(rawQualityAcknowledgements);
    } catch {
      /* ignore invalid JSON */
    }
  }

  let provenancesMap: Record<string, any> = {};
  const rawProvenances = form.get("provenances");
  if (typeof rawProvenances === "string") {
    try {
      provenancesMap = JSON.parse(rawProvenances);
    } catch {
      /* ignore invalid JSON */
    }
  }

  let receiptsMap: Record<string, any> = {};
  const rawReceipts = form.get("receipts");
  if (typeof rawReceipts === "string") {
    try {
      receiptsMap = JSON.parse(rawReceipts);
    } catch {
      /* ignore invalid JSON */
    }
  }

  let visualApprovalsMap: Record<string, any> = {};
  const rawVisualApprovals = form.get("visualApprovals");
  if (typeof rawVisualApprovals === "string") {
    try {
      visualApprovalsMap = JSON.parse(rawVisualApprovals);
    } catch {
      /* ignore invalid JSON */
    }
  }

  // ──────────────────────────────────────────────────
  // 1. Resolve the authoritative layout plan
  // ──────────────────────────────────────────────────
  let plan;
  try {
    plan = resolveLayoutPlan({
      child,
      bookId: bookId ?? "dream-big",
      profileId: profileId ?? "classic-landscape-11x8",
      mode,
      customSpreads,
    });
  } catch (err: any) {
    return NextResponse.json(
      { error: `Layout resolution failed: ${err.message ?? err}` },
      { status: 400 },
    );
  }

  // ──────────────────────────────────────────────────
  // 2. Run authoritative import resolution through matchImportedFiles()
  //    This is the SINGLE place where filenames are matched to slots.
  // ──────────────────────────────────────────────────
  const filenames = files.map((f) => f.name);
  const importReport = matchImportedFiles(filenames, plan.assets, {
    bookId,
    confirmLegacyOffsetRecovery: confirmLegacyOffsetRecovery || legacyInterpretation === "SHIFT_PLUS_TWO",
    legacyInterpretation,
  });

  // ──────────────────────────────────────────────────
  // 3. HTTP 409: Ambiguous legacy package requires user choice
  // ──────────────────────────────────────────────────
  if (importReport.legacyRecoveryProposal && importReport.legacyRecoveryChoices) {
    return NextResponse.json(
      {
        code: "LEGACY_MAPPING_CONFIRMATION_REQUIRED",
        error: "Ambiguous file package — please select an interpretation.",
        message: importReport.legacyRecoveryProposal,
        choices: importReport.legacyRecoveryChoices.map((c) => ({
          interpretation: c.interpretation,
          label: c.label,
          description: c.description,
          mappingTable: c.mappingTable.map((m) => ({
            filename: m.filename,
            targetSlotId: m.proposedSlotId,
            role: m.role,
            physicalPage: m.physicalPages,
          })),
          resultingMissingSlots: c.resultingMissingSlots.map((s) => ({
            slotId: s.slotId,
            physicalPages: s.physicalPages,
            role: s.role,
            expectedFilename: s.expectedFilename,
          })),
        })),
      },
      { status: 409 },
    );
  }

  // ──────────────────────────────────────────────────
  // 4. Check for missing slots after resolution
  // ──────────────────────────────────────────────────
  if (!isDraft && importReport.missingSlotDetails && importReport.missingSlotDetails.length > 0) {
    return NextResponse.json(
      {
        code: "MISSING_REQUIRED_ARTWORK",
        error: "Cannot export production PDF: required artwork is missing.",
        missingSlots: importReport.missingSlotDetails.map((s) => ({
          slotId: s.slotId,
          physicalPages: s.physicalPages,
          role: s.role,
          expectedFilename: s.expectedFilename,
        })),
      },
      { status: 400 },
    );
  }

  // ──────────────────────────────────────────────────
  // 5. Build slotId-keyed image maps from authoritative resolution
  // ──────────────────────────────────────────────────
  const fileByName = new Map<string, File>(files.map((f) => [f.name, f]));
  const resolvedSlotMapping = new Map<string, ProvidedImage>();
  const resolvedSlotFileMapping = new Map<string, { filename: string; buffer: Buffer }>();

  for (const [slotId, filename] of importReport.bySlotId) {
    const file = fileByName.get(filename);
    if (!file) continue;
    const buffer = Buffer.from(await file.arrayBuffer());
    const slotIndex = plan.assets.findIndex((s) => s.slotId === slotId);
    resolvedSlotMapping.set(slotId, {
      buffer,
      mimeType: file.type || "image/png",
      transform: slotIndex >= 0 && transformsMap[slotIndex]
        ? sanitizeTransform(transformsMap[slotIndex])
        : undefined,
    });
    resolvedSlotFileMapping.set(slotId, { filename, buffer });
  }

  // ──────────────────────────────────────────────────
  // 6. Run preflight with pre-resolved mapping (no independent re-matching)
  // ──────────────────────────────────────────────────
  if (!isDraft) {
    const preflightFiles: PreflightFile[] = [];
    const preflightSlotMapping = new Map<string, PreflightFile>();

    for (const [slotId, entry] of resolvedSlotFileMapping) {
      const prov = provenancesMap[slotId] ?? provenancesMap[entry.filename];
      const receipt = receiptsMap[slotId] ?? receiptsMap[entry.filename] ?? prov?.receipt;
      const pfFile: PreflightFile = {
        filename: entry.filename,
        buffer: entry.buffer,
        provenance: prov,
        receipt,
      };
      preflightFiles.push(pfFile);
      preflightSlotMapping.set(slotId, pfFile);
    }

    const preflight = await runPreflight({
      child,
      bookId,
      profileId,
      files: preflightFiles,
      mode,
      customSpreads,
      resolvedSlotMapping: preflightSlotMapping,
      acknowledgeQualityWarnings,
      qualityAcknowledgements,
      visualApprovals: visualApprovalsMap,
      provenances: provenancesMap,
      receipts: receiptsMap,
    });

    if (preflightOnly) {
      return NextResponse.json({
        ok: preflight.ok,
        preflight,
        issues: preflight.issues ?? [],
        qualityWarnings: preflight.qualityWarnings ?? [],
      });
    }

    // HTTP 409: Quality warnings require explicit acknowledgement
    if (!preflight.ok && preflight.qualityWarnings && preflight.qualityWarnings.length > 0) {
      const onlyQualityIssues = preflight.issues?.every(
        (i) => i.type === "QUALITY_WARNING_UNACKNOWLEDGED",
      );
      if (onlyQualityIssues) {
        return NextResponse.json(
          {
            code: "QUALITY_WARNING_ACKNOWLEDGEMENT_REQUIRED",
            error: "Images between 150-299 PPI require explicit acknowledgement for production export.",
            qualityWarnings: preflight.qualityWarnings,
            issues: preflight.issues,
          },
          { status: 409 },
        );
      }
    }

    if (!preflight.ok) {
      const missingArtworkIssues = preflight.issues?.filter((i) => i.type === "MISSING_REQUIRED_ARTWORK");
      if (missingArtworkIssues && missingArtworkIssues.length > 0) {
        return NextResponse.json(
          {
            code: "MISSING_REQUIRED_ARTWORK",
            error: "Cannot export production PDF: required artwork is missing.",
            missingSlots: missingArtworkIssues.map((i) => ({
              slotId: (i as any).slotId ?? i.filename ?? "unknown",
              physicalPages: (i as any).physicalPages ?? [i.illustrationNumber ?? 1],
            })),
            issues: preflight.issues,
            preflight,
          },
          { status: 400 },
        );
      }

      const issues = preflight.issues && preflight.issues.length > 0
        ? preflight.issues
        : preflight.errors.map((err) => ({
            type: "PREFLIGHT_ERROR",
            message: err,
          }));
      return NextResponse.json(
        {
          code: "PREFLIGHT_FAILED",
          error: "Preflight validation failed — production export blocked.",
          issues,
          preflight,
          qualityWarnings: preflight.qualityWarnings ?? [],
        },
        { status: 400 },
      );
    }
  }

  // ──────────────────────────────────────────────────
  // 7. Assemble PDF using authoritative slot mapping
  // ──────────────────────────────────────────────────
  let pdf: Buffer;
  try {
    // Also build a legacy numeric map for backward compat with the assembler's
    // existing fallback paths (canonical filename, legacy aliases)
    const images = new Map<number | string, ProvidedImage>();
    for (const [slotId, img] of resolvedSlotMapping) {
      images.set(slotId, img);
    }

    const rawVideoUrl = form.get("videoUrl");
    const videoTarget =
      typeof rawVideoUrl === "string" && rawVideoUrl.trim().length > 0
        ? directVideoTarget(rawVideoUrl.trim())
        : undefined;

    const assembled = await assembleFromImages(child, images, bookId, profileId, {
      mode,
      layoutMode: mode,
      customSpreads,
      draft: isDraft,
      confirmLegacyOffsetRecovery: confirmLegacyOffsetRecovery || legacyInterpretation === "SHIFT_PLUS_TWO",
      resolvedSlotMapping,
      videoTarget,
    });
    pdf = assembled.pdf;
  } catch (err: any) {
    if (err?.code === "MISSING_REQUIRED_ARTWORK" || err?.name === "MissingArtworkError") {
      return NextResponse.json(
        {
          code: "MISSING_REQUIRED_ARTWORK",
          error: "Cannot export production PDF: required artwork is missing.",
          missingSlots: err.missingSlots ?? [],
        },
        { status: 400 },
      );
    }
    if (err?.code === "INVALID_VIDEO_QR" || err?.name === "InvalidVideoQrError") {
      return NextResponse.json(
        {
          code: "INVALID_VIDEO_QR",
          error: err.message ?? "Cannot export production PDF: the video-qr page is not production-ready.",
          reason: err.reason ?? null,
        },
        { status: 400 },
      );
    }
    throw err;
  }

  // Keep a per-child folder with the images, prompts, and finished PDF.
  try {
    await saveRun({
      child,
      bookId,
      pdf,
      images: [...resolvedSlotMapping.entries()].map(([_slotId, img], i) => ({
        index: i,
        data: img.buffer,
        mimeType: img.mimeType,
      })),
    });
  } catch (err) {
    console.warn("[storybook] could not save run to disk:", err);
  }

  return new Response(new Uint8Array(pdf), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${bookFilename(child.name, bookId)}"`,
      "Content-Length": String(pdf.length),
    },
  });
}
