/**
 * POST /api/assemble
 *
 * Free path: build the print-ready PDF from images the user generated by hand.
 * Multipart form with name/age/gender + image files (named 01.png, 02.png, …).
 * Returns the PDF directly — assembly takes a few seconds, so no polling needed.
 */

import { NextResponse } from "next/server";
import { z } from "zod";
import {
  assembleFromImages,
  indexFromFilename,
  type ProvidedImage,
} from "@/lib/manual/assemble";
import { saveRun } from "@/lib/generate/saveRun";
import { bookFilename } from "@/lib/story/registry";
import type { ChildProfile } from "@/lib/story/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

const profileSchema = z.object({
  name: z.string().trim().min(1, "Name is required").max(40),
  age: z.coerce.number().int().min(0).max(18),
  gender: z.enum(["boy", "girl", "neutral"]),
});

export async function POST(request: Request): Promise<Response> {
  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return NextResponse.json(
      { error: "Expected multipart/form-data." },
      { status: 400 },
    );
  }

  const parsed = profileSchema.safeParse({
    name: form.get("name"),
    age: form.get("age"),
    gender: form.get("gender"),
  });
  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues[0]?.message ?? "Invalid input." },
      { status: 400 },
    );
  }
  const child: ChildProfile = parsed.data;

  const files = form
    .getAll("images")
    .filter((f): f is File => f instanceof File && f.size > 0);
  if (files.length === 0) {
    return NextResponse.json(
      { error: "Please add your generated images (named 01.png, 02.png, …)." },
      { status: 400 },
    );
  }

  // Pair each image with its page by the leading number in the filename.
  const images = new Map<number, ProvidedImage>();
  for (const file of files) {
    const index = indexFromFilename(file.name);
    if (index === null) continue;
    const buffer = Buffer.from(await file.arrayBuffer());
    images.set(index, { buffer, mimeType: file.type || "image/png" });
  }

  if (images.size === 0) {
    return NextResponse.json(
      { error: "Couldn't match any images to pages. Name them 01.png, 02.png, …" },
      { status: 400 },
    );
  }

  const bookId = (form.get("bookId") as string) || undefined;
  const profileId = (form.get("profileId") as string) || undefined;
  const { pdf } = await assembleFromImages(child, images, bookId, profileId);

  // Keep a per-child folder with the images, prompts, and finished PDF.
  try {
    await saveRun({
      child,
      bookId,
      pdf,
      images: [...images.entries()].map(([index, img]) => ({
        index,
        data: img.buffer,
        mimeType: img.mimeType,
      })),
    });
  } catch (err) {
    console.warn("[storybook] could not save run to disk:", err);
  }

  return new Response(new Uint8Array(pdf), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${bookFilename(child.name, bookId)}"`,
      "Content-Length": String(pdf.length),
    },
  });
}
