/**
 * POST /api/assemble-printify
 *
 * Printify path: run preflight, then export a print-ready folder (cover.png,
 * page-NN.png, proof.pdf, prompts.md, order-info.txt) to the local
 * storybook-out/ folder from images the user generated by hand. Unlike
 * /api/assemble, this never streams a file back — it writes to disk (item 20)
 * and returns a JSON summary, since the deliverable is a folder of files, not
 * a single PDF.
 */

import { NextResponse } from "next/server";
import { z } from "zod";
import { indexFromFilename, type ProvidedImage } from "@/lib/manual/assemble";
import { exportPrintifyBook } from "@/lib/print/printifyExport";
import { sanitizeTransform, type ArtworkTransform } from "@/lib/print/artworkTransform";
import { resolveLayoutPlan } from "@/lib/story/layoutPlan";
import { matchImportedFiles } from "@/lib/manual/importMatch";
import type { ChildProfile } from "@/lib/story/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 120;

const profileSchema = z.object({
  name: z.string().trim().min(1, "Name is required").max(40),
  age: z.coerce.number().int().min(0).max(18),
  gender: z.enum(["boy", "girl", "neutral"]),
  profileId: z.string().trim().min(1, "Print profile is required"),
});

export async function POST(request: Request): Promise<Response> {
  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return NextResponse.json(
      { error: "Expected multipart/form-data." },
      { status: 400 },
    );
  }

  const parsed = profileSchema.safeParse({
    name: form.get("name"),
    age: form.get("age"),
    gender: form.get("gender"),
    profileId: form.get("profileId"),
  });
  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues[0]?.message ?? "Invalid input." },
      { status: 400 },
    );
  }
  const child: ChildProfile = {
    name: parsed.data.name,
    age: parsed.data.age,
    gender: parsed.data.gender,
  };
  const { profileId } = parsed.data;

  const files = form
    .getAll("images")
    .filter((f): f is File => f instanceof File && f.size > 0);
  if (files.length === 0) {
    return NextResponse.json(
      { error: "Please add your generated images (named 01.png, 02.png, …)." },
      { status: 400 },
    );
  }

  let transformsMap: Record<string, ArtworkTransform> = {};
  const rawTransforms = form.get("transforms");
  if (typeof rawTransforms === "string") {
    try {
      transformsMap = JSON.parse(rawTransforms);
    } catch {
      /* ignore invalid JSON */
    }
  }

  let provenancesMap: Record<string, any> = {};
  const rawProvenances = form.get("provenances");
  if (typeof rawProvenances === "string") {
    try {
      provenancesMap = JSON.parse(rawProvenances);
    } catch {
      /* ignore invalid JSON */
    }
  }

  let receiptsMap: Record<string, any> = {};
  const rawReceipts = form.get("receipts");
  if (typeof rawReceipts === "string") {
    try {
      receiptsMap = JSON.parse(rawReceipts);
    } catch {
      /* ignore invalid JSON */
    }
  }

  const rawAck = form.get("acknowledgeQualityWarnings");
  const acknowledgeQualityWarnings = rawAck === "true" || rawAck === "1";

  let qualityAcknowledgements: Record<string, any> = {};
  const rawQualityAcknowledgements = form.get("qualityAcknowledgements");
  if (typeof rawQualityAcknowledgements === "string") {
    try {
      qualityAcknowledgements = JSON.parse(rawQualityAcknowledgements);
    } catch {
      /* ignore invalid JSON */
    }
  }

  const bookId = (form.get("bookId") as string) || undefined;
  const rawMode = ((form.get("layoutMode") as string) || (form.get("mode") as string)) || null;
  const mode = rawMode === "custom-spreads" || rawMode === "standard-single" ? rawMode : undefined;
  let customSpreads: any = undefined;
  const rawSpreads = form.get("customSpreads");
  if (typeof rawSpreads === "string") {
    try {
      customSpreads = JSON.parse(rawSpreads);
    } catch {
      /* ignore invalid JSON */
    }
  }

  const plan = resolveLayoutPlan({
    child,
    bookId: bookId ?? "dream-big",
    profileId,
    mode,
    customSpreads,
  });

  const filenames = files.map((f) => f.name);
  const importReport = matchImportedFiles(filenames, plan.assets, { bookId });

  const fileByName = new Map<string, File>(files.map((f) => [f.name, f]));
  const images = new Map<number, ProvidedImage>();
  const rawFiles: { filename: string; buffer: Buffer }[] = [];
  const preflightSlotMapping = new Map<string, any>();

  for (const [slotId, filename] of importReport.bySlotId) {
    const file = fileByName.get(filename);
    if (!file) continue;
    const buffer = Buffer.from(await file.arrayBuffer());
    const slot = plan.assets.find((s: any) => s.slotId === slotId);
    const slotIndex = slot ? slot.illustrationIndex : -1;
    const prov = provenancesMap[slotId] ?? provenancesMap[filename];
    const receipt = receiptsMap[slotId] ?? receiptsMap[filename] ?? prov?.receipt;

    rawFiles.push({ filename, buffer });
    if (slotIndex >= 0) {
      images.set(slotIndex, {
        buffer,
        mimeType: file.type || "image/png",
        transform: transformsMap[slotIndex] ? sanitizeTransform(transformsMap[slotIndex]) : undefined,
      });
    }

    preflightSlotMapping.set(slotId, {
      filename,
      buffer,
      provenance: prov,
      receipt,
    });
  }

  const result = await exportPrintifyBook({
    child,
    bookId,
    profileId,
    images,
    rawFiles,
    mode,
    customSpreads,
    provenances: provenancesMap,
    receipts: receiptsMap,
    resolvedSlotMapping: preflightSlotMapping,
    qualityAcknowledgements,
    acknowledgeQualityWarnings,
  });

  if (!result.ok) {
    const issues = result.preflight.issues && result.preflight.issues.length > 0
      ? result.preflight.issues
      : result.preflight.errors.map((err) => ({
          type: "PREFLIGHT_ERROR",
          message: err,
        }));
    return NextResponse.json(
      {
        code: "PREFLIGHT_FAILED",
        error: "Preflight failed — nothing was exported.",
        issues,
        preflight: result.preflight,
      },
      { status: 400 },
    );
  }

  return NextResponse.json({
    dir: result.dir,
    files: result.files,
    warnings: result.preflight.warnings,
  });
}
