/**
 * POST /api/assemble-printify
 *
 * Printify path: run preflight, then export a print-ready folder (cover.png,
 * page-NN.png, proof.pdf, prompts.md, order-info.txt) to the local
 * storybook-out/ folder from images the user generated by hand. Unlike
 * /api/assemble, this never streams a file back — it writes to disk (item 20)
 * and returns a JSON summary, since the deliverable is a folder of files, not
 * a single PDF.
 */

import { NextResponse } from "next/server";
import { z } from "zod";
import { indexFromFilename, type ProvidedImage } from "@/lib/manual/assemble";
import { exportPrintifyBook } from "@/lib/print/printifyExport";
import { sanitizeTransform, type ArtworkTransform } from "@/lib/print/artworkTransform";
import type { ChildProfile } from "@/lib/story/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 120;

const profileSchema = z.object({
  name: z.string().trim().min(1, "Name is required").max(40),
  age: z.coerce.number().int().min(0).max(18),
  gender: z.enum(["boy", "girl", "neutral"]),
  profileId: z.string().trim().min(1, "Print profile is required"),
});

export async function POST(request: Request): Promise<Response> {
  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return NextResponse.json(
      { error: "Expected multipart/form-data." },
      { status: 400 },
    );
  }

  const parsed = profileSchema.safeParse({
    name: form.get("name"),
    age: form.get("age"),
    gender: form.get("gender"),
    profileId: form.get("profileId"),
  });
  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues[0]?.message ?? "Invalid input." },
      { status: 400 },
    );
  }
  const child: ChildProfile = {
    name: parsed.data.name,
    age: parsed.data.age,
    gender: parsed.data.gender,
  };
  const { profileId } = parsed.data;

  const files = form
    .getAll("images")
    .filter((f): f is File => f instanceof File && f.size > 0);
  if (files.length === 0) {
    return NextResponse.json(
      { error: "Please add your generated images (named 01.png, 02.png, …)." },
      { status: 400 },
    );
  }

  let transformsMap: Record<string, ArtworkTransform> = {};
  const rawTransforms = form.get("transforms");
  if (typeof rawTransforms === "string") {
    try {
      transformsMap = JSON.parse(rawTransforms);
    } catch {
      /* ignore invalid JSON */
    }
  }

  const rawFiles: { filename: string; buffer: Buffer }[] = [];
  const images = new Map<number, ProvidedImage>();
  for (const file of files) {
    const buffer = Buffer.from(await file.arrayBuffer());
    rawFiles.push({ filename: file.name, buffer });
    const index = indexFromFilename(file.name);
    if (index === null) continue;
    images.set(index, {
      buffer,
      mimeType: file.type || "image/png",
      transform: transformsMap[index] ? sanitizeTransform(transformsMap[index]) : undefined,
    });
  }
  if (images.size === 0) {
    return NextResponse.json(
      { error: "Couldn't match any images to pages. Name them 01.png, 02.png, …" },
      { status: 400 },
    );
  }

  const bookId = (form.get("bookId") as string) || undefined;

  const result = await exportPrintifyBook({ child, bookId, profileId, images, rawFiles });

  if (!result.ok) {
    return NextResponse.json(
      { error: "Preflight failed — nothing was exported.", preflight: result.preflight },
      { status: 400 },
    );
  }

  return NextResponse.json({
    dir: result.dir,
    files: result.files,
    warnings: result.preflight.warnings,
  });
}
