/**
 * CLI: assemble the print-ready PDF from images you generated by hand.
 *
 *   npm run assemble -- --dir storybook-out/alex
 *
 * Reads the child profile from <dir>/manifest.json (or from --name/--age/--gender),
 * pairs each image in <dir>/images/ with its page by the leading number in the
 * filename, and writes <dir>/<slug>-dream-big.pdf.
 */

import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { parseArgs } from "node:util";
import {
  assembleFromImages,
  indexFromFilename,
  type ProvidedImage,
} from "../lib/manual/assemble";
import { uniquePath } from "../lib/generate/paths";
import { bookFilename, DEFAULT_BOOK_ID } from "../lib/story/registry";
import type { ChildProfile, Gender } from "../lib/story/types";

function fail(message: string): never {
  console.error(`\n✖ ${message}\n`);
  console.error("Usage: npm run assemble -- --dir <dir> [--name <name> --age 4 --gender boy]\n");
  process.exit(1);
}

const MIME: Record<string, string> = {
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
};

async function resolveProfile(
  dir: string,
  values: Record<string, string | undefined>,
): Promise<{ child: ChildProfile; bookId: string }> {
  let manifestChild: ChildProfile | undefined;
  let manifestBookId: string | undefined;
  try {
    const parsed = JSON.parse(await readFile(path.join(dir, "manifest.json"), "utf8"));
    if (parsed?.child?.name) manifestChild = parsed.child as ChildProfile;
    if (typeof parsed?.bookId === "string") manifestBookId = parsed.bookId;
  } catch {
    /* no manifest — rely on flags */
  }

  const bookId = values.book ?? manifestBookId ?? DEFAULT_BOOK_ID;

  if (values.name) {
    const age = Number(values.age ?? "4");
    const gender = (values.gender ?? "boy") as Gender;
    return { child: { name: values.name, age, gender }, bookId };
  }
  if (manifestChild) return { child: manifestChild, bookId };

  fail("Provide --name (and optional --age/--gender), or run prompts first so manifest.json exists.");
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      dir: { type: "string" },
      name: { type: "string" },
      age: { type: "string" },
      gender: { type: "string" },
      book: { type: "string" },
    },
  });

  if (!values.dir) fail("Missing --dir");
  const dir = values.dir;
  const { child, bookId } = await resolveProfile(dir, values);

  const imagesDir = path.join(dir, "images");
  let entries: string[];
  try {
    entries = await readdir(imagesDir);
  } catch {
    fail(`No images folder at ${imagesDir}`);
  }

  const images = new Map<number, ProvidedImage>();
  for (const file of entries.sort()) {
    const ext = path.extname(file).toLowerCase();
    const mimeType = MIME[ext];
    if (!mimeType) continue;
    const index = indexFromFilename(file);
    if (index === null) continue;
    const buffer = await readFile(path.join(imagesDir, file));
    images.set(index, { buffer, mimeType });
  }

  if (images.size === 0) {
    fail(`No usable images found in ${imagesDir} (name them 01.png, 02.png, …).`);
  }

  console.log(`\nAssembling "${bookId}" PDF for ${child.name} from ${images.size} images …`);
  const { pdf, usedPages, totalPages } = await assembleFromImages(child, images, bookId);

  // Never overwrite a previous PDF: a clash becomes …_1.pdf, etc.
  const outPath = uniquePath(path.join(dir, bookFilename(child.name, bookId)));
  await writeFile(outPath, pdf);

  console.log(`✓ Wrote ${outPath}`);
  console.log(`   ${usedPages}/${totalPages} pages had images` +
    (usedPages < totalPages ? " (missing pages use a soft fallback background).\n" : ".\n"));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
